### ISSUE TITLE
Update attribute instead of moving around array

### ISSUE THREAD

**Issue by ridnarong** [ridnarong/angular-intern#1]
As I mention about update attribute for example sensor.match="left | right | null". This way is more effective way to do search and filtering.

**Comment by Indradwi22** [comment]
Excuse me, Mr Ridnarong.
Sorry, I still don't understand, How can I do it, Mr Ridnarong?
Should I use 'ng-show' and change my algorithm?
Do you have references, Mr Ridnarong?
Because, I just know my algorithm.

**Comment by ridnarong** [comment]
In sensor list use ng-show="sensor.match == 'matched'"
In left panel use ng-show="sensor.match == 'left'"
In left panel use ng-show="sensor.match == 'right'"

Each place use ng-repeat

**Comment by Indradwi22** [comment]
Okey, Mr. Ridnarong. I will try....
Thank you...
