### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by ridnarong** [ridnarong/angular-intern#2]
1. Just show input box no need to click button to see it.
2. I think you should set enteredValue=null instead of "" when no value in input box or when you want to clear the value.
3. We do search in sensor level then it will show only matched result.
4. << and >> should be in sensor level
   ![search](https://cloud.githubusercontent.com/assets/1758378/8270732/0ed87062-181a-11e5-97ac-bf81431dddcf.png)
5. Search input should be non-case sensitive (eg: Temp == temp)

**Comment by Indradwi22** [comment]
Okey Mr Ridnarong.
I'll try to do it....
Thank you...
